CREATE TABLE `Vehicle` (
`id` INTEGER NOT NULL AUTO_INCREMENT DEFAULT NULL ,
`VIN` VARCHAR(30) DEFAULT NULL ,
`Make` VARCHAR(30) DEFAULT NULL ,
`Model` VARCHAR(30) DEFAULT NULL ,
`PurchaseDate` DATETIME DEFAULT NULL ,
PRIMARY KEY (`id`)
) COMMENT='Table for storing vehicle details';